core/urls.py
from django.urls import path

from .views import (index, result_station, add_samplingfeatures, add_time_serie_values, add_units, add_time_serie_result, add_data_results,
                    add_processing_level, add_action, add_method, add_organization, add_variable, station_info)

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('station/<code>/result', result_station, name='result_station'),
    path('station/add', add_samplingfeatures, name='station'),
    path('station/<code>/add_data', add_time_serie_values, name='add_values'),
    path('add_data', add_time_serie_values, name='add'),
    path('units/add', add_units, name='units'),
    path('result_series/add', add_time_serie_result, name='results_serie_results'),
    path('data_results/add', add_data_results, name='data_results'),
    path('processing/add', add_processing_level, name='processing_level'),
    path('action/add', add_action, name='action'),
    path('variable/add', add_variable, name='variable'),
    path('method/add', add_method, name='method'),
    path('organization/add', add_organization, name='org'),
    path('station/<code>', station_info, name='station_info')
]

envflow/urls.py
from django.contrib import admin
from django.urls import path, include
from ajax_select import views as ajax_select_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('iha/', include('iha.urls'), name='iha'),
    path('', include('core.urls'), name='core'),
    path('lookups/(<channel>[-\w]+)', ajax_select_views.ajax_lookup, name='ajax_lookup'),
    path('user/', include('user.urls'), name='user')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iha/urls.py
from django.urls import path
from .views import index, results


app_name = 'iha'

urlpatterns = [
    path('<code>', index, name='index'),
    path('#', results, name='results'),
]

user/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import register

app_name = 'user'

urlpatterns = [
    path('register', register, name='register'),
    path('login', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', LogoutView.as_view(template_name='index.html'), name='logout'),
]

core/views.py
import os

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.storage import default_storage
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, resolve
from django.views.generic import CreateView
from django.contrib.gis.geos import Point

from core.forms import UnitsForm, ResultsForm, ProcessingLevelsForm, FeatureAcrionForm, ActionsForm, MethodsForm, \
    ActionMultiForm, VariablesForm
from envflow.settings import MEDIA_ROOT
from .forms import SamplingFeaturesForm, TimeResultsSeriesValuesForm, OrganizationsForm, TimeSeriesResultsForm
from odm2admin.models import Samplingfeatures, Timeseriesresultvalues, Featureactions, CvSamplingfeaturetype, \
    Organizations, Units, Timeseriesresults, Results, Processinglevels, Actions, Methods, CvCensorcode, CvQualitycode, \
    Variables
import pandas as pd
from hydrocomp.series.flow import Flow
import plotly.offline as opy


# Create your views here.
class IndexView(CreateView):

    model = Samplingfeatures
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):

        samplingfeatures = Samplingfeatures.objects.all()
        features = Featureactions.objects.all()

        context = {'samplingfeatures': samplingfeatures,
                   'features': features}

        return render(request, self.template_name, context)


class ResultStationView(CreateView):

    template_name = 'result_station.html'

    def get(self, request, *args, **kwargs):

        featureaction = Featureactions.objects.get(pk=kwargs['code'])
        data = Timeseriesresultvalues.objects.filter(
            resultid__resultid__featureactionid_id=featureaction.featureactionid).values_list('datavalue',
                                                                                              'valuedatetime')
        station = featureaction.samplingfeatureid.samplingfeaturename

        dic = {'Data': [], station: []}
        for i in data:
            dic['Data'].append(i[1])
            dic[station].append(i[0])
        data_flow = pd.DataFrame(dic, index=dic['Data'], columns=[station])
        flow = Flow(data=data_flow, station=station)
        fig_hydro, data_hydro = flow.hydrogram()
        hydrogram = opy.plot(fig_hydro,  include_plotlyjs=True, output_type='div', auto_open=False)

        fig_hydro_by_year, data_hydro_by_year = flow.hydrogram_year()
        hydro_by_year = opy.plot(fig_hydro_by_year, include_plotlyjs=True, output_type='div', auto_open=False)

        month = flow.get_month_name()
        q710 = flow.flow_min('q710')

        context = {"featureaction": featureaction,
                   'hydrogram': hydrogram,
                   'hydro_by_year': hydro_by_year,
                   'month': month,
                   'mean': '{:.3f}'.format(flow.mean()[0]),
                   'q95': '{:.3f}'.format(flow.quantile(0.05)[0]),
                   'min': '{:.3f}'.format(flow.data.min().values[0]),
                   'max': '{:.3f}'.format(flow.data.max().values[0]),
                   'q710': '{:.3f}'.format(q710)
                   }

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        stations = Samplingfeatures.objects.all()

        context = {'stations': stations}

        return render(request, self.template_name, context)


class AddSamplingFeaturesView(LoginRequiredMixin, CreateView):

    model = Samplingfeatures
    form_class = SamplingFeaturesForm
    template_name = 'sampling.html'
    success_url = reverse_lazy('core:index')

    def post(self, request, *args, **kwargs):
        post = request.POST
        name = post['samplingfeaturename']
        code = post['samplingfeaturecode']
        feature_type = CvSamplingfeaturetype.objects.get(pk=post['sampling_feature_type'])
        lat = post['lat']
        lon = post['lon']
        point = Point(float(lat), float(lon))

        sampling = Samplingfeatures(samplingfeaturecode=code, samplingfeaturename=name, featuregeometry=point,
                                    sampling_feature_type=feature_type)

        sampling.save()
        return redirect(self.success_url)


class AddOrganizationsView(LoginRequiredMixin, CreateView):

    model = Organizations
    form_class = OrganizationsForm
    template_name = 'organizations.html'
    success_url = reverse_lazy('core:index')


class AddTimeResultsSeriesValuesView(LoginRequiredMixin, CreateView):

    model = Timeseriesresultvalues
    form_class = TimeResultsSeriesValuesForm
    template_name = 'time_serie_values.html'
    success_url = reverse_lazy('core:index')

    def get(self, request, *args, **kwargs):

        context = {}
        if 'code' in kwargs.keys():
            sampling = Samplingfeatures.objects.get(samplingfeaturecode=kwargs['code'])
            context["sampling"] = sampling

        context["form"] = self.form_class

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        post = request.POST
        file = request.FILES['File']

        sampling = Samplingfeatures.objects.get(samplingfeaturecode=kwargs['code'])

        path = default_storage.save('data_file/%s' % file.name, file)
        file = os.path.abspath(os.path.join(MEDIA_ROOT, path))

        result = Timeseriesresults.objects.get(pk=post['resultid'])
        censor = CvCensorcode.objects.get(pk=post['censorcodecv'])
        quality = CvQualitycode.objects.get(pk=post['qualitycodecv'])
        units_time = Units.objects.get(pk=post['timeaggregationintervalunitsid'])
        time_inter = post['timeaggregationinterval']
        value_utc = post['valuedatetimeutcoffset']

        source = 'ANA'

        station = sampling.samplingfeaturename
        print(station.upper())

        dados = Flow(path=file, source=source.upper(), station=station.upper(), consistence=2)
        default_storage.delete(path)
        dados.data = dados.data.dropna()
        time_serie_result_list = []
        print(dados.data)

        for i in dados.data.index:
            obj_ts = Timeseriesresultvalues(resultid=result, censorcodecv=censor,
                                            qualitycodecv=quality, valuedatetimeutcoffset=value_utc,
                                            timeaggregationinterval=time_inter,
                                            timeaggregationintervalunitsid=units_time,
                                            valuedatetime=i.to_datetime(),
                                            datavalue=float(dados.data[dados.data.columns.values[0]][i]))

            time_serie_result_list.append(obj_ts)
        Timeseriesresultvalues.objects.bulk_create(time_serie_result_list)
        return redirect(self.success_url)


class AddUnitsView(LoginRequiredMixin, CreateView):

    model = Units
    form_class = UnitsForm
    template_name = 'units.html'
    success_url = reverse_lazy('core:index')

    def get(self, request, *args, **kwargs):
        url = resolve('/'+'/'.join(request.META.get("HTTP_REFERER").split('/')[3:]))
        self.success_url = reverse_lazy('{}:{}'.format(url.app_name, url.url_name))
        context = {'form': self.form_class}
        return render(request, self.template_name, context=context)


class AddTimeSeriesResultView(LoginRequiredMixin, CreateView):

    model = Timeseriesresults
    form_class = TimeSeriesResultsForm
    template_name = 'time_serie_result.html'
    success_url = reverse_lazy('core:index')


class AddDataResultsView(LoginRequiredMixin, CreateView):

    model = Results
    template_name = 'data_results.html'
    form_class = ResultsForm
    success_url = reverse_lazy('core:index')


class AddProcessingLevelsView(LoginRequiredMixin, CreateView):

    model = Processinglevels
    template_name = 'processing_level.html'
    form_class = ProcessingLevelsForm
    success_url = reverse_lazy('core:index')


class AddActionView(LoginRequiredMixin, CreateView):

    model = Actions
    form_class = ActionMultiForm
    template_name = 'action.html'
    success_url = reverse_lazy('core:index')


class AddMethodsView(LoginRequiredMixin, CreateView):

    model = Methods
    form_class = MethodsForm
    template_name = 'method.html'
    success_url = reverse_lazy('core:index')


class AddVariablesView(LoginRequiredMixin, CreateView):
    model = Variables
    form_class = VariablesForm
    template_name = 'variable.html'
    success_url = reverse_lazy('core:variable')


class StationInfoView(CreateView):

    template_name = 'station_info.html'

    def get(self, request, *args, **kwargs):

        station = Samplingfeatures.objects.get(samplingfeaturecode=kwargs['code'])
        features = Featureactions.objects.filter(samplingfeatureid=station.samplingfeatureid)

        context = {
            'station': station,
            'features': features,
        }

        return render(request, self.template_name, context=context)


index = IndexView.as_view()
result_station = ResultStationView.as_view()
add_samplingfeatures = AddSamplingFeaturesView.as_view()
add_time_serie_values = AddTimeResultsSeriesValuesView.as_view()
add_units = AddUnitsView.as_view()
add_time_serie_result = AddTimeSeriesResultView.as_view()
add_data_results = AddDataResultsView.as_view()
add_processing_level = AddProcessingLevelsView.as_view()
add_variable = AddVariablesView.as_view()
add_action = AddActionView.as_view()
add_method = AddMethodsView.as_view()
add_organization = AddOrganizationsView.as_view()
station_info = StationInfoView.as_view()

core/templates/action.html
{% extends "add_data.html" %}

{% block title %}
    Ação
{% endblock %}

core/templates/add_data.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block container %}
<div class="col-md-9">
        <div class="col-md-10 col-md-offset-0">
            <div class="page-header">
                <h2>{% block title %}{% endblock %}</h2>
            </div>
            <div class="page-header">
                <form class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset>
                        {% for field in form %}
                            <div class="form-group">
                                <label for="{{ field.auto_id }}" class="col-md-9 control-label required">
                                    {{ field.label }}
                                </label>
                                <div class="col-md-9">
                                    <div class="related-widget-wrapper">
                                        {{ field|add_class:'form-control' }}
                                    </div>
                                </div>

                            </div>
                        {% endfor %}
                        <div class="form-group POST">
                            <div class="col-md-9 col-md-offset-3">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>FlowIHA</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

    <script type="text/javascript" src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
    <script type="text/javascript" src="{% static 'ajax_select/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'ajax_select/js/ajax_select.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/admin/DateTimeShortcuts.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/calendar.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'core:index' %}">
            <div class="sidebar-brand-text mx-3">FlowIHA</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
            Dados
        </div>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
               aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-coins"></i>
                <span>Adicionar</span>
            </a>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Adicionar:</h6>
                    <a class="collapse-item" href="{% url 'core:org' %}">Organização</a>
                    <a class="collapse-item" href="{% url 'core:station' %}">Estação</a>
                    <a class="collapse-item" href="{% url 'core:action' %}">Ação</a>
                    <a class="collapse-item" href="{% url 'core:variable' %}">Variável</a>
                    <a class="collapse-item" href="{% url 'core:units' %}">Unidade</a>
                    <a class="collapse-item" href="{% url 'core:processing_level' %}">Nível de Processamento</a>
                    <a class="collapse-item" href="{% url 'core:data_results' %}">Resultado dos dados</a>
                    <a class="collapse-item" href="{% url 'core:results_serie_results' %}">Resul. de Série Temporal</a>
                    <a class="collapse-item" href="{% url 'core:add' %}">Valor de Série Temporal</a>
                </div>
            </div>
        </li>

        <!-- Nav Item - Utilities Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
               aria-expanded="true" aria-controls="collapseUtilities">
                <i class="fas fa-fw fa-wrench"></i>
                <span>Utilities</span>
            </a>
            <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                 data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Custom Utilities:</h6>
                    <a class="collapse-item" href="{$utilities-color.html">Colors</a>
                    <a class="collapse-item" href="utilities-border.html">Borders</a>
                    <a class="collapse-item" href="utilities-animation.html">Animations</a>
                    <a class="collapse-item" href="utilities-other.html">Other</a>
                </div>
            </div>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
            Addons
        </div>

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"
               aria-controls="collapsePages">
                <i class="fas fa-fw fa-folder"></i>
                <span>Pages</span>
            </a>
            <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Login Screens:</h6>
                    <a class="collapse-item" href="{% url 'user:login' %}">Login</a>
                    <a class="collapse-item" href="{% url 'user:register' %}">Register</a>
                    <a class="collapse-item" href="#">Forgot Password</a>
                </div>
            </div>
        </li>

        <!-- Nav Item - Charts -->
        <li class="nav-item">
            <a class="nav-link" href="charts.html">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>Charts</span></a>
        </li>

        <!-- Nav Item - Tables -->
        <li class="nav-item">
            <a class="nav-link" href="tables.html">
                <i class="fas fa-fw fa-table"></i>
                <span>Tables</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>

                {% block search %}{% endblock %}

                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">

                    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                    <li class="nav-item dropdown no-arrow d-sm-none">
                        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-search fa-fw"></i>
                        </a>
                        <!-- Dropdown - Messages -->
                        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                             aria-labelledby="searchDropdown">
                            <form class="form-inline mr-auto w-100 navbar-search">
                                <div class="input-group">
                                    <input type="text" class="form-control bg-light border-0 small"
                                           placeholder="Search for..." aria-label="Search"
                                           aria-describedby="basic-addon2">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="button">
                                            <i class="fas fa-search fa-sm"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </li>

                    <div class="topbar-divider d-none d-sm-block"></div>

                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">
                        {% if user.is_authenticated %}
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-lg-inline text-gray-600 small">{{ user.people }}</span>
                                <img class="img-profile rounded-circle" src="{{ user.profile_picture.url }}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'user:logout' %}" data-toggle="modal"
                                   data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        {% else %}
                            <a class="nav-link dropdown-toggle" aria-haspopup="true" aria-expanded="false"
                               href="{% url 'user:login' %}">Login</a>
                        {% endif %}
                    </li>
                </ul>
            </nav>
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">
                {% block container %}{% endblock %}
            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Flow &copy; 2019</span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="{% url 'user:logout' %}">Logout</a>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

core/templates/data_results.html
{% extends "add_data.html" %}

{% block title %}
    Resultados dos Dados
{% endblock %}

core/templates/index.html
<!DOCTYPE html>
<html lang="en">

{% extends "base.html" %}

{% load static %}
{% block search %}
    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                   aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>
{% endblock %}

{% block container %}
    {% load leaflet_tags %}
    {% leaflet_css plugins="ALL" %}
    {% leaflet_js plugins="ALL" %}

    <div>
        {% leaflet_map "main" callback="map_init" %}
    </div>

    <div id="mapid">
        <style>
            .leaflet-container {
                width: 100%;
                height: 600px
            }
        </style>
        <script type="text/javascript">
            function map_init(map, options) {
                {% for sampling in samplingfeatures %}
                    // get point lat and lon
                    var lat = "{{ sampling.featuregeometrywkt.x }}";
                    var lon = "{{ sampling.featuregeometrywkt.y }}";
                    // zoom to point & add it to map
                    var name = '<h6><a class="m-0 font-weight-bold text-primary" href="{% url 'core:station_info' sampling.samplingfeaturecode %}">{{ sampling.samplingfeaturename }}</a></h6>'
                    var la = '<br>Lat: {{ sampling.featuregeometrywkt.x }}</br>'
                    var lo = '<br>Lon: {{ sampling.featuregeometrywkt.y }}</br>'
                    var iha = '<p><a class="m-0 font-weight-bold text-primary" href={% url 'iha:index' sampling.samplingfeaturecode %}>IHA</a></p>'

                    {% if user.is_authenticated %}
                        var user = '<h6><a class="m-0 font-weight-bold text-primary" href="{% url 'core:add_values' sampling.samplingfeaturecode %}">Adicionar dados</a></h6>'
                    {% else %}
                        var user = ''
                    {% endif %}
                    var method = ''
                    {% for feature in features %}
                        {% if feature.samplingfeatureid.samplingfeaturename == sampling.samplingfeaturename %}
                            var method = method + '<p><a class="m-0 font-weight-bold text-primary" href="{%  url 'core:result_station' feature.featureactionid %}">{{ feature.action.method.methodname }}</a></p>'
                        {% else %}
                            var method = method + ''
                        {% endif %}
                    {% endfor %}
                    L.marker([lat, lon]).bindPopup(name + user + method + iha + la + lo).openPopup().addTo(map);
                {% endfor %}
            }
        </script>
    </div>
{% endblock %}

core/templates/organizations.html
{% extends "add_data.html" %}

{% block title %}
    Organização
{% endblock %}

core/templates/sampling.html
{% extends "add_data.html" %}

{% block title %}
    Estação
{% endblock %}

core/templates/station_info.html
{% extends 'base.html' %}

{% block container %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Estação: {{ station.samplingfeaturename }}</h1>
    </div>
    <div class="row">
        <!-- Area Chart -->
        <div class="col-xl-12 col-lg-7">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Informações</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Mínima</h6>
                    </div>
                    {% for feature in features %}
                        <p><a class="m-0 font-weight-bold text-primary"
                              href="{% url 'core:result_station' feature.featureactionid %}">{{ feature.action.method.methodname }}</a>
                        </p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/time_serie_result.html
{% extends "add_data.html" %}

{% block title %}
    Resultados de séries temporais
{% endblock %}

core/templates/time_serie_values.html
{% extends "add_data.html" %}

{% block title %}
    {% if sampling.samplingfeaturename == None %}
        Valor/Série Temporal
    {% else %}
        Valor/Série Temporal - {{ sampling.samplingfeaturename }}
    {% endif %}
{% endblock %}

core/templates/units.html
{% extends "add_data.html" %}

{% block title %}
    Unidade
{% endblock %}